language: nix

env:
  - PY=python26
  - PY=python27
  - PY=python33
  - PY=python34
  - PY=python35
  - PY=python36
  - PY=pypy

script:
- if [ "$TRAVIS_PULL_REQUEST" != "true" -a "$TRAVIS_BRANCH" = "master" ]; then
    nix-build release.nix -A sampleproject."$PY";
  fi

matrix:
  allow_failures:
    - env: PY=python26
